### ISSUE TITLE
Request email verification feature

### ISSUE THREAD

**Issue by quyentruong** [kennethtomagan/laravel-6-api-boilerplate#13]
Hello Kenneth,

This API is awesome and helpful for my personal project. Can you add email verification ? It's kind of useful for users to reset their password if they put correct email address.

**Comment by kennethtomagan** [comment]
Hi @quyentruong ,

The Laravel API Boilerplate already has an email verification feature. 
Setup your `.env` file for notification functionality
```
MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
```
Also, Add your frontend URL in `.env` files to redirect the user into your fontend App. 
```
FRONTEND_APP_URL =http://localhost:8080/
```

**Comment by quyentruong** [comment]
I mean users need to verify their email after register. They will receive an email about verification. After they click on a link or button in the email, the column **email_verified** in the users table will show **true**

**Comment by ninearif** [comment]
> I mean users need to verify their email after register. They will receive an email about verification. After they click on a link or button in the email, the column **email_verified** in the users table will show **true**

you can implement MustVerifyEmail interface that already included in the User model
https://github.com/kennethtomagan/laravel-6-api-boilerplate/blob/d897d505d5ba54e42066632b8871579b7f43c76e/app/User.php#L6

by adding to this line
https://github.com/kennethtomagan/laravel-6-api-boilerplate/blob/d897d505d5ba54e42066632b8871579b7f43c76e/app/User.php#L10

and do the rest following this document
https://laravel.com/docs/6.x/verification

**Comment by kennethtomagan** [comment]
Just change the `ACCOUNT_VERIFY=true` in `.env` file. 
It will enable the account verification of the APP.
