### ISSUE TITLE
Logout route not working in postman

### ISSUE THREAD

**Issue by sahilkashyap64** [kennethtomagan/laravel-6-api-boilerplate#25]
```
{
    "error": "",
    "status_code": 0
}
```
This comes everytime when I try to use logout route. Maybe some issue regarding regarding the logout controller or because of the code in Exception handler. Kindly see into it.

**Comment by kennethtomagan** [comment]
I tried it lately and it's working. 
if you still encounter that error try this:
1. Check your .env file especially on database config. 
2. make sure to access the logout using "POST" method. 
3. double-check your route. https://documenter.getpostman.com/view/880526/SVtN3BkG?version=latest

I'm sure that you try to access the wrong endpoint.

**Comment by kennethtomagan** [comment]
@sahilkashyap64 I pushed an update,
 if the route is not found it returns an error message.
