### ISSUE TITLE
Login and logout always using database 'users', and in network database we need to create user

### ISSUE THREAD

**Issue by MrAlexanderWs** [kennethtomagan/laravel-6-api-boilerplate#26]
I think this code is works when I using my local database. But when I changed to my network and database, which doesn't have table users, it won't work. I am using my table xin_employees, to test login and logout from database dmi_hrm_indako, these tables hasn't id when I logout. When I changed User to XinEmployee like in these picture, so I could login and logout from xin_employees table using username and password.
![Screenshot from 2020-05-28 11-50-01](https://user-images.githubusercontent.com/46021397/83100476-41793a80-a0da-11ea-907c-461c43972f04.png)
![Screenshot from 2020-05-28 11-57-16](https://user-images.githubusercontent.com/46021397/83100554-6d94bb80-a0da-11ea-89e0-2548a7473ef2.png)
![Screenshot from 2020-05-28 11-57-57](https://user-images.githubusercontent.com/46021397/83100579-7dac9b00-a0da-11ea-9519-5b56188ef164.png)

it won't work in AuthController2 (Note. I duplicate previously worked AuthController and I rename it to AuthController2 for my project). And also I had create apps and Resource, which change User to XinEmployees, it won't work when I tested in Postman. It always throw user tables in dmi_hrm_indako which doesn't have table users.
![Screenshot from 2020-05-28 12-00-57](https://user-images.githubusercontent.com/46021397/83100801-f0b61180-a0da-11ea-8479-a068a7b12e03.png)

It only works when I modify or add table users in my network database like in these pictures
![Screenshot from 2020-05-28 12-03-17](https://user-images.githubusercontent.com/46021397/83100913-412d6f00-a0db-11ea-9299-a841ef2a4af0.png)

My network database : dmi_hrm_indako
My table used to test API : xin_employees (using username and password)

Anyone can help this issues?

**Comment by kennethtomagan** [comment]
First, Go to config/auth.php
then change the value of model key under providers.user. 
example: 
**config/auth.php**

```
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],
    ],
```
to

```
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\XinEmployee::class,
        ],
    ],
```
make sure you have XinEmployee model, 

and last thing, that is not a boilerplate issue btw.

**Comment by MrAlexanderWs** [comment]
Thank you. This is not a boilerplate issues, because i test it works. This is about I test login and logout by using network databases. The second is I cannot logout. Should I change the auth.php, or in Resources, remove the ID in user? I copy an existed User Resources and change name to XinEmployees.php, so when I logout, it shows errors even I changed in Resources\User.php to remove ID. 

![Screenshot from 2020-05-28 14-14-46](https://user-images.githubusercontent.com/46021397/83111016-26182a80-a0ee-11ea-801b-0778924a0fbe.png)
This is 'user_id' which is used to login and logout, in table xin_employees. 

![Screenshot from 2020-05-28 14-07-47](https://user-images.githubusercontent.com/46021397/83110521-65924700-a0ed-11ea-99d4-431692a455a7.png)
This is the result when I can login, but I can't logout, it shows in my database hasn't column 'id' even i change in my XinEmployees resources

![Screenshot from 2020-05-28 14-11-01](https://user-images.githubusercontent.com/46021397/83110529-6925ce00-a0ed-11ea-8f75-196dae9ba692.png)
This is the default of User Resources

![Screenshot from 2020-05-28 14-14-46](https://user-images.githubusercontent.com/46021397/83110705-ad18d300-a0ed-11ea-8018-877a393a0f83.png)
This is the Resources which i used to login and logout using my existing database

Anyone can help this? If i modify the id it won't work.

**Comment by kennethtomagan** [comment]
in Logout controller, 
remove this code:
`auth()->logout()`
instead use this code to logout or invalidate token 
`\JWTAuth::invalidate(\JWTAuth::getToken());`


btw, click the star button if you think the boilerplate helps you :)

**Comment by MrAlexanderWs** [comment]
Ok. I give it stars. This project works, but because I am new of API and I'm using network website to login and logout unlike normally

I check there is no `auth()->logout()` in LogoutController.php, and
`\JWTAuth::invalidate(\JWTAuth::getToken());`, it won't work. 

It always shows this `
error: "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' (SQL: select * from xin_employees where `id` is null limit 1)",
    "status_code": "42S22"`. It only works when I add `id` in `xin_employees `table. But in xin_employees table already have `user_id` column

![Screenshot from 2020-05-28 14-52-25](https://user-images.githubusercontent.com/46021397/83114245-f0297500-a0f2-11ea-89ff-297e3b954bbb.png)
This is my LogoutController

I make another resource XinEmployees so when i login and logout only using username and password
![Screenshot from 2020-05-28 14-56-37](https://user-images.githubusercontent.com/46021397/83114744-94abb700-a0f3-11ea-960d-2b3fb0c683f1.png)

I don't know why I logout always need `id `although I already have `user_id` to used for logout in my existed tables.

**Comment by MrAlexanderWs** [comment]
I forget something. If I change 
`use Illuminate\Foundation\Auth\User as Authenticatable;` to 
`use Illuminate\Foundation\Auth\XinEmployees as Authenticatable;`

it shows  `
"error": "Class 'Illuminate\\Foundation\\Auth\\XinEmployees' not found",
    "status_code": 0.` Does it affect to logout?

**Comment by MrAlexanderWs** [comment]
@kennethtomagan I just tried to get my profile from my current username
![Screenshot from 2020-05-29 09-48-19](https://user-images.githubusercontent.com/46021397/83215603-962bbc80-a191-11ea-86b5-e25726e29aa2.png)

But when I get the selected profile, it always shows the first username only, not the selected username, even I using the same token that I logged in via postman.
![Screenshot from 2020-05-29 09-48-23](https://user-images.githubusercontent.com/46021397/83215611-9a57da00-a191-11ea-9df9-40932c135b77.png)

And this is my `ProfileController.php`.
![Screenshot from 2020-05-29 09-49-05](https://user-images.githubusercontent.com/46021397/83215676-b9566c00-a191-11ea-8d20-e8e1a1caa0a6.png)

Should I added the query in this controller like this?
`$query = $this->db->query("SELECT * FROM xin_employees where username = '$xin_employees'");`

**Comment by kennethtomagan** [comment]
try to use `request()->user();`
then I advise to add `id` column in your xin_employees  table.

**Comment by MrAlexanderWs** [comment]
I have tried using this method in my network database : 
`request()->user(); `in 

```
public function me(Request $request)
    {
        
        $user = $request->user();
        //$user = Auth::user();
        
        $data = new XinEmployeesResource($user);

        return response()->json(compact('data'));
        //return $query->result();

    }
```
I have tested in my local default database, it works. However, it doesn't work at my network database
This is my test with my local database
![Screenshot from 2020-05-29 15-53-44](https://user-images.githubusercontent.com/46021397/83241142-9a250200-a1c4-11ea-98b7-c412954e8fc2.png)


It won't work if I using my network database. It still shows first username not selected username even I using same token from different usernames. Even I updated the password, it only updated the first username not the selected username. But if I using my local database, it works when I updated a profile and/or password. 

This is my comparison from previous code with my code with Meld. I just change xin_employees to get data from selected employees, but it returns first employees.
![Screenshot from 2020-05-29 16-01-46](https://user-images.githubusercontent.com/46021397/83242761-1c162a80-a1c7-11ea-9d0d-97315e38de3c.png)


This is my resources
![Screenshot from 2020-05-29 15-59-23](https://user-images.githubusercontent.com/46021397/83241675-63032080-a1c5-11ea-975d-984b3c1c5873.png)

**Comment by MrAlexanderWs** [comment]
@kennethtomagan This is my database
![Screenshot from 2020-06-01 16-49-08](https://user-images.githubusercontent.com/46021397/83399955-4a487400-a42c-11ea-9e67-afecb89722b4.png)
![Screenshot from 2020-06-01 16-49-20](https://user-images.githubusercontent.com/46021397/83399964-4ddbfb00-a42c-11ea-952f-98eef4f7cdb1.png)
![Screenshot from 2020-06-01 16-49-24](https://user-images.githubusercontent.com/46021397/83399971-503e5500-a42c-11ea-9771-f95dfba2c946.png)
![Screenshot from 2020-06-01 16-49-29](https://user-images.githubusercontent.com/46021397/83399979-53d1dc00-a42c-11ea-8b71-c782e2063ae1.png)
![Screenshot from 2020-06-01 16-49-31](https://user-images.githubusercontent.com/46021397/83399985-559b9f80-a42c-11ea-816b-88d40bf5bc07.png)
![Screenshot from 2020-06-01 16-49-33](https://user-images.githubusercontent.com/46021397/83399993-59c7bd00-a42c-11ea-80de-8108b53ffcab.png)

I used this code in my profile controller, it only shows the first username, not the selected username. The id tables is i created. Or should I make trigger ID is same as user ID
```
public function me(Request $request)
    {
        
        //$xin_employees = Auth::user();
        $xin_employees = $request->user();
        
        $data = new XinEmployeesResource($xin_employees);

        return response()->json(compact('data'));

    }
```

Anyone can help this?

**Comment by kennethtomagan** [comment]
I closed this issue because it's not related to boilerplate. 
Thank you.
